name: CMake

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install correct version of mingw
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install mingw --version=8.1.0  -y

      - name: Install Qt
        uses: jurplel/install-qt-action@v3.1.0
        with:
          version: "6.3.1"
          host: "windows"
          target: "desktop"
          arch: "win64_mingw81"
          dir: "${{github.workspace}}/qt/"
          install-deps: "true"

      - name: Configure CMake
        env:
          CMAKE_PREFIX_PATH: ${{env.Qt6_Dir}}
        run: cmake -DCMAKE_PREFIX_PATH=${{env.Qt6_Dir}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -B ${{github.workspace}}/build -G "CodeBlocks - MinGW Makefiles"

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
